### ISSUE TITLE
no Icons in Nextcloud with Office Online Server

### ISSUE THREAD

**Issue by TheMrg** [nextcloud/officeonline#144]
See Screenshot.

https://outoosserver/hosting/discovery works.

<img width="261" alt="2021-04-28 18_34_55-Dateien - Nextcloud" src="https://user-images.githubusercontent.com/38321123/116440238-8fe60a80-a850-11eb-889f-11302ef4502e.png">

**Comment by koelle25** [comment]
I just noticed the same issue and further inspected it. CSS-Value for the icon comes from icons.css and is:
```css
.icon-filetype-document {
  background-image: url(data:image/svg+xml;base64,ZXhwb3J0IGRlZmF1bHQgImRhdGE6aW1hZ2Uvc3ZnK3htbDtiYXNlNjQsUEhOMlp5QjRiV3h1Y3owaWFIUjBjRG92TDNkM2R5NTNNeTV2Y21jdk1qQXdNQzl6ZG1jaUlIWnBaWGRDYjNnOUlqQWdNQ0F4TmlBeE5pSWdkMmxrZEdnOUlqRTJJaUIyWlhKemFXOXVQU0l4TGpFaUlHaGxhV2RvZEQwaU1UWWlQanh3WVhSb0lHWnBiR3c5SWlNME9XRmlaV0VpSUdROUltMHlMalVnTVdNdE1DNHlPQ0F3TFRBdU5TQXdMakl5TFRBdU5TQXdMalYyTVROak1DQXdMakk0SURBdU1qSWdNQzQxSURBdU5TQXdMalZvTVRGak1DNHlPQ0F3SURBdU5TMHdMakl5SURBdU5TMHdMalYyTFRFd0xqVnNMVE10TTJndE9DNDFlbTB4TGpVZ01tZzJkakZvTFRaMkxURjZiVEFnTTJnMWRqRm9MVFYyTFRGNmJUQWdNMmc0ZGpGb0xUaDJMVEY2YlRBZ00yZzBkakZvTFRSMkxURjZJaTgrUEM5emRtYytDZz09Ig==)
}
```

I then decoded the contained base64 encoded string and got this:
```
export default "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxNiAxNiIgd2lkdGg9IjE2IiB2ZXJzaW9uPSIxLjEiIGhlaWdodD0iMTYiPjxwYXRoIGZpbGw9IiM0OWFiZWEiIGQ9Im0yLjUgMWMtMC4yOCAwLTAuNSAwLjIyLTAuNSAwLjV2MTNjMCAwLjI4IDAuMjIgMC41IDAuNSAwLjVoMTFjMC4yOCAwIDAuNS0wLjIyIDAuNS0wLjV2LTEwLjVsLTMtM2gtOC41em0xLjUgMmg2djFoLTZ2LTF6bTAgM2g1djFoLTV2LTF6bTAgM2g4djFoLTh2LTF6bTAgM2g0djFoLTR2LTF6Ii8+PC9zdmc+Cg=="
```

Decoding this again finally results in the SVG data:
```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" width="16" version="1.1" height="16"><path fill="#49abea" d="m2.5 1c-0.28 0-0.5 0.22-0.5 0.5v13c0 0.28 0.22 0.5 0.5 0.5h11c0.28 0 0.5-0.22 0.5-0.5v-10.5l-3-3h-8.5zm1.5 2h6v1h-6v-1zm0 3h5v1h-5v-1zm0 3h8v1h-8v-1zm0 3h4v1h-4v-1z"/></svg>
```

So it seems that the actual SVG data is being encoded two times in the process, either at runtime or already at build time. It may even be because the data is encoded when building the app AND at runtime. A dev should have a look at it.
